apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-ingress: "true"
spec:
  rules:
    - host: coinvault.com
      http:
        paths:
          - path: /api/trades
            pathType: Prefix
            backend:
              service:
                name: trades-clusterip-srv
                port:
                  number: 80
          - path: /api/portfolios
            pathType: Prefix
            backend:
              service:
                name: portfolios-clusterip-srv
                port:
                  number: 80
