apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolios-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolioservice
  template:
    metadata:
      labels:
        app: portfolioservice
    spec:
      containers:
        - name: portfolioservice
          image: robfontys/coin-vault-microservice-portfolio:latest
          resources:
            limits:
              memory: "350Mi"
              cpu: 500m
            requests:
              memory: "64Mi"
              cpu: 100m
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: portfolios-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: portfolios-depl
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
---
apiVersion: v1
kind: Service
metadata:
  name: portfolios-clusterip-srv
spec:
  type: ClusterIP
  selector: 
    app: portfolioservice
  ports: 
  - name: portfolioservice
    protocol: TCP
    port: 80
    targetPort: 80