apiVersion: apps/v1
kind: Deployment
metadata:
  name: trades-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tradingservice
  template:
    metadata:
      labels:
        app: tradingservice
    spec:
      containers:
        - name: tradingservice
          image: robfontys/coin-vault-microservice-trade:latest
          resources:
            limits:
              memory: "350Mi"
              cpu: 500m
            requests:
              memory: "64Mi"
              cpu: 100m
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: trades-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trades-depl
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
---
apiVersion: v1
kind: Service
metadata:
  name: trades-clusterip-srv
spec:
  type: ClusterIP
  selector: 
    app: tradingservice
  ports: 
  - name: tradingservice
    protocol: TCP
    port: 80
    targetPort: 80